spring.application.name=habittt

# Server Port
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/habittt?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis-Plus Configuration
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.id-type=auto

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Mail Configuration (For Forgot Password)
# QQ
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=3131641975@qq.com
spring.mail.password=fzyezeorlgsxdfig
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB